### ISSUE TITLE
Error prepData function

### ISSUE THREAD

**Issue by nayaracleite** [HelenaLC/CATALYST#141]
Hi, I am getting the error below in with the prepData function. I checked the ids in the samples_filtered and md (metadata) and they are the same. Do you have any idea what could be happening?

`> all(panel$fcs_colname %in% colnames(samples_filtered))`
[1] TRUE

```
> prepData(samples_filtered, panel, md, features = panel$fcs_colname)
```
Error in prepData(samples_filtered, panel, md, features = panel$fcs_colname) : 
  all(ids %in% md[[md_cols$file]]) is not TRUE

```
> fsApply(samples_filtered, identifier)  
```                  
PBMC_ND_Alpha.fcs          "PBMC_ND_Alpha.fcs"         
PBMC_ND_Beta.fcs           "PBMC_ND_Beta.fcs"          
PBMC_ND_PMA.fcs            "PBMC_ND_PMA.fcs"           
PBMC_ND_Unstimulated.fcs   "PBMC_ND_Unstimulated.fcs"  
PBMC_T1D1_Alpha.fcs        "PBMC_T1D1_Alpha.fcs"       
PBMC_T1D1_Beta.fcs         "PBMC_T1D1_Beta.fcs"        
PBMC_T1D1_PMA.fcs          "PBMC_T1D1_PMA.fcs"         
PBMC_T1D1_Unstimulated.fcs "PBMC_T1D1_Unstimulated.fcs"
PBMC_T1D2_Alpha.fcs        "PBMC_T1D2_Alpha.fcs"       
PBMC_T1D2_Beta.fcs         "PBMC_T1D2_Beta.fcs"        
PBMC_T1D2_PMA.fcs          "PBMC_T1D2_PMA.fcs"         
PBMC_T1D2_Unstimulated.fcs "PBMC_T1D2_Unstimulated.fcs"
PBMC_T1D3_Alpha.fcs        "PBMC_T1D3_Alpha.fcs"       
PBMC_T1D3_Beta.fcs         "PBMC_T1D3_Beta.fcs"        
PBMC_T1D3_PMA.fcs          "PBMC_T1D3_PMA.fcs"         
PBMC_T1D3_Unstimulated.fcs "PBMC_T1D3_Unstimulated.fcs"

```
> md$file_name
```
 [1] PBMC_ND_Alpha.fcs          PBMC_ND_Beta.fcs           PBMC_ND_PMA.fcs            PBMC_ND_Unstimulated.fcs  
 [5] PBMC_T1D1_Alpha.fcs        PBMC_T1D1_Beta.fcs         PBMC_T1D1_PMA.fcs          PBMC_T1D1_Unstimulated.fcs
 [9] PBMC_T1D2_Alpha.fcs        PBMC_T1D2_Beta.fcs         PBMC_T1D2_PMA.fcs          PBMC_T1D2_Unstimulated.fcs
[13] PBMC_T1D3_Alpha.fcs        PBMC_T1D3_Beta.fcs         PBMC_T1D3_PMA.fcs          PBMC_T1D3_Unstimulated.fcs
16 Levels: PBMC_ND_Alpha.fcs PBMC_ND_Beta.fcs PBMC_ND_PMA.fcs PBMC_ND_Unstimulated.fcs ... PBMC_T1D3_Unstimulated.fcs

**Comment by HelenaLC** [comment]
Could you please post the output of your session info? There was an issue with this in early version, which I’d like to rule out.

**Comment by nayaracleite** [comment]
[session_info.txt](https://github.com/HelenaLC/CATALYST/files/5261902/session_info.txt)
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Debian GNU/Linux 10 (buster)
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2020-09-22                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package                * version  date       lib source        
   abind                    1.4-5    2016-07-21 [2] CRAN (R 3.6.2)
   AnnotationDbi            1.48.0   2019-10-29 [2] Bioconductor  
   AnnotationHub          * 2.18.0   2019-10-29 [1] Bioconductor  
   assertthat               0.2.1    2019-03-21 [2] CRAN (R 3.6.2)
   base64enc                0.1-3    2015-07-28 [2] CRAN (R 3.6.2)
   beeswarm                 0.2.3    2016-04-25 [1] CRAN (R 3.6.2)
   Biobase                * 2.46.0   2019-10-29 [2] Bioconductor  
   BiocFileCache          * 1.10.2   2019-11-08 [2] Bioconductor  
   BiocGenerics           * 0.32.0   2019-10-29 [2] Bioconductor  
 P BiocManager            * 1.30.10  2019-11-16 [2] CRAN (R 3.6.2)
   BiocNeighbors            1.4.2    2020-02-29 [1] Bioconductor  
   BiocParallel           * 1.20.1   2019-12-21 [2] Bioconductor  
   BiocSingular             1.2.2    2020-02-14 [1] Bioconductor  
   BiocStyle              * 2.14.4   2020-01-09 [1] Bioconductor  
   BiocVersion              3.10.1   2019-06-06 [2] Bioconductor  
   bit                      1.1-15   2020-01-13 [2] CRAN (R 3.6.2)
   bit64                    0.9-7    2017-05-08 [2] CRAN (R 3.6.2)
   bitops                   1.0-6    2013-08-17 [2] CRAN (R 3.6.2)
   blob                     1.2.0    2019-07-09 [2] CRAN (R 3.6.2)
   boot                     1.3-24   2019-12-20 [3] CRAN (R 3.6.2)
   car                      3.0-9    2020-08-11 [1] CRAN (R 3.6.2)
   carData                  3.0-4    2020-05-22 [1] CRAN (R 3.6.2)
   CATALYST               * 1.10.3   2020-04-02 [1] Bioconductor  
   cellranger               1.1.0    2016-07-27 [2] CRAN (R 3.6.2)
   circlize                 0.4.10   2020-06-15 [1] CRAN (R 3.6.2)
   cli                      2.0.2    2020-02-28 [1] CRAN (R 3.6.2)
   clue                     0.3-57   2019-02-25 [1] CRAN (R 3.6.2)
   cluster                  2.1.0    2019-06-19 [3] CRAN (R 3.6.2)
   codetools                0.2-16   2018-12-24 [3] CRAN (R 3.6.2)
   colorspace               1.4-1    2019-03-18 [2] CRAN (R 3.6.2)
   ComplexHeatmap           2.2.0    2019-10-29 [1] Bioconductor  
   ConsensusClusterPlus     1.50.0   2019-10-29 [1] Bioconductor  
   corpcor                  1.6.9    2017-04-01 [1] CRAN (R 3.6.2)
   cowplot                * 1.1.0    2020-09-08 [1] CRAN (R 3.6.2)
   crayon                   1.3.4    2017-09-16 [2] CRAN (R 3.6.2)
   curl                     4.3      2019-12-02 [2] CRAN (R 3.6.2)
   CytoML                   1.12.1   2020-03-26 [1] Bioconductor  
   data.table               1.13.0   2020-07-24 [1] CRAN (R 3.6.2)
   DBI                      1.1.0    2019-12-15 [2] CRAN (R 3.6.2)
   dbplyr                 * 1.4.2    2019-06-17 [2] CRAN (R 3.6.2)
   DelayedArray           * 0.12.3   2020-04-09 [1] Bioconductor  
   DelayedMatrixStats       1.8.0    2019-10-29 [1] Bioconductor  
   DEoptimR                 1.0-8    2016-11-19 [2] CRAN (R 3.6.2)
   diffcyt                * 1.6.6    2020-04-07 [1] Bioconductor  
   digest                   0.6.25   2020-02-23 [1] CRAN (R 3.6.2)
   dplyr                    1.0.2    2020-08-18 [1] CRAN (R 3.6.2)
   drc                      3.0-1    2016-08-30 [1] CRAN (R 3.6.2)
   DT                       0.15     2020-08-05 [1] CRAN (R 3.6.2)
   edgeR                    3.28.0   2019-10-29 [2] Bioconductor  
   ellipse                  0.4.2    2020-05-27 [1] CRAN (R 3.6.2)
   ellipsis                 0.3.1    2020-05-15 [1] CRAN (R 3.6.2)
   evaluate                 0.14     2019-05-28 [2] CRAN (R 3.6.2)
   ExperimentHub          * 1.12.0   2019-10-29 [1] Bioconductor  
   fansi                    0.4.1    2020-01-08 [1] CRAN (R 3.6.2)
   fastmap                  1.0.1    2019-10-08 [2] CRAN (R 3.6.2)
   fda                      5.1.5.1  2020-08-02 [1] CRAN (R 3.6.2)
   flowClust                3.24.0   2019-10-29 [1] Bioconductor  
   flowCore               * 1.52.1   2019-12-04 [1] Bioconductor  
   FlowSOM                  1.18.0   2019-10-29 [1] Bioconductor  
   flowStats                3.44.0   2019-10-29 [1] Bioconductor  
   flowViz                  1.50.0   2019-10-29 [1] Bioconductor  
   flowWorkspace            3.34.1   2020-01-02 [1] Bioconductor  
   forcats                  0.5.0    2020-03-01 [1] CRAN (R 3.6.2)
   foreign                  0.8-74   2019-12-26 [3] CRAN (R 3.6.2)
   generics                 0.0.2    2018-11-29 [2] CRAN (R 3.6.2)
   GenomeInfoDb           * 1.22.1   2020-03-27 [1] Bioconductor  
   GenomeInfoDbData         1.2.2    2020-01-13 [2] Bioconductor  
   GenomicRanges          * 1.38.0   2019-10-29 [2] Bioconductor  
   GetoptLong               1.0.2    2020-07-06 [1] CRAN (R 3.6.2)
   ggbeeswarm               0.6.0    2017-08-07 [1] CRAN (R 3.6.2)
   ggcyto                   1.14.1   2020-03-07 [1] Bioconductor  
   ggplot2                * 3.3.2    2020-06-19 [1] CRAN (R 3.6.2)
   ggrepel                  0.8.2    2020-03-08 [1] CRAN (R 3.6.2)
   ggridges                 0.5.2    2020-01-12 [2] CRAN (R 3.6.2)
   GlobalOptions            0.1.2    2020-06-10 [1] CRAN (R 3.6.2)
   glue                     1.4.2    2020-08-27 [1] CRAN (R 3.6.2)
   graph                    1.64.0   2019-10-29 [1] Bioconductor  
   gridExtra                2.3      2017-09-09 [2] CRAN (R 3.6.2)
   gtable                   0.3.0    2019-03-25 [2] CRAN (R 3.6.2)
   gtools                   3.8.2    2020-03-31 [1] CRAN (R 3.6.2)
   haven                    2.3.1    2020-06-01 [1] CRAN (R 3.6.2)
   HDCytoData             * 1.6.6    2020-01-21 [1] Bioconductor  
   hexbin                   1.28.1   2020-02-03 [1] CRAN (R 3.6.2)
   hms                      0.5.3    2020-01-08 [2] CRAN (R 3.6.2)
   htmltools                0.5.0    2020-06-16 [1] CRAN (R 3.6.2)
   htmlwidgets              1.5.1    2019-10-08 [2] CRAN (R 3.6.2)
   httpuv                   1.5.4    2020-06-06 [1] CRAN (R 3.6.2)
   httr                     1.4.2    2020-07-20 [1] CRAN (R 3.6.2)
   IDPmisc                  1.1.20   2020-01-21 [1] CRAN (R 3.6.2)
   igraph                   1.2.5    2020-03-19 [1] CRAN (R 3.6.2)
   interactiveDisplayBase   1.24.0   2019-10-29 [1] Bioconductor  
   IRanges                * 2.20.2   2020-01-13 [1] Bioconductor  
   irlba                    2.3.3    2019-02-05 [2] CRAN (R 3.6.2)
   jpeg                     0.1-8.1  2019-10-24 [2] CRAN (R 3.6.2)
   jsonlite                 1.7.1    2020-09-07 [1] CRAN (R 3.6.2)
   KernSmooth               2.23-16  2019-10-15 [3] CRAN (R 3.6.2)
   knitr                  * 1.26     2019-11-12 [2] CRAN (R 3.6.2)
   ks                       1.11.7   2020-02-11 [1] CRAN (R 3.6.2)
   later                    1.1.0.1  2020-06-05 [1] CRAN (R 3.6.2)
   lattice                  0.20-38  2018-11-04 [3] CRAN (R 3.6.2)
   latticeExtra             0.6-29   2019-12-19 [2] CRAN (R 3.6.2)
   lazyeval                 0.2.2    2019-03-15 [2] CRAN (R 3.6.2)
   lifecycle                0.2.0    2020-03-06 [1] CRAN (R 3.6.2)
   limma                    3.42.0   2019-10-29 [2] Bioconductor  
   lme4                     1.1-23   2020-04-07 [1] CRAN (R 3.6.2)
   locfit                   1.5-9.1  2013-04-20 [2] CRAN (R 3.6.2)
   magrittr                 1.5      2014-11-22 [2] CRAN (R 3.6.2)
   MASS                     7.3-51.5 2019-12-20 [3] CRAN (R 3.6.2)
   Matrix                   1.2-18   2019-11-27 [1] CRAN (R 3.6.2)
   matrixStats            * 0.56.0   2020-03-13 [1] CRAN (R 3.6.2)
   mclust                   5.4.6    2020-04-11 [1] CRAN (R 3.6.2)
   memoise                  1.1.0    2017-04-21 [2] CRAN (R 3.6.2)
   mime                     0.9      2020-02-04 [1] CRAN (R 3.6.2)
   minqa                    1.2.4    2014-10-09 [2] CRAN (R 3.6.2)
   mnormt                   2.0.2    2020-09-01 [1] CRAN (R 3.6.2)
   multcomp                 1.4-12   2020-01-10 [2] CRAN (R 3.6.2)
   munsell                  0.5.0    2018-06-12 [2] CRAN (R 3.6.2)
   mvtnorm                  1.1-1    2020-06-09 [1] CRAN (R 3.6.2)
   ncdfFlow                 2.32.0   2019-10-29 [1] Bioconductor  
   nlme                     3.1-143  2019-12-10 [3] CRAN (R 3.6.2)
   nloptr                   1.2.2.2  2020-07-02 [1] CRAN (R 3.6.2)
   nnls                     1.4      2012-03-19 [1] CRAN (R 3.6.2)
   openCyto                 1.24.0   2019-10-29 [1] Bioconductor  
   openxlsx                 4.2.2    2020-09-17 [1] CRAN (R 3.6.2)
   packrat                  0.5.0    2018-11-14 [2] CRAN (R 3.6.2)
   pcaPP                    1.9-73   2018-01-14 [1] CRAN (R 3.6.2)
   pillar                   1.4.6    2020-07-10 [1] CRAN (R 3.6.2)
   pkgconfig                2.0.3    2019-09-22 [2] CRAN (R 3.6.2)
   plotly                   4.9.1    2019-11-07 [2] CRAN (R 3.6.2)
   plotrix                  3.7-7    2019-12-05 [2] CRAN (R 3.6.2)
   plyr                     1.8.6    2020-03-03 [1] CRAN (R 3.6.2)
   png                      0.1-7    2013-12-03 [2] CRAN (R 3.6.2)
   promises                 1.1.1    2020-06-09 [1] CRAN (R 3.6.2)
   purrr                    0.3.4    2020-04-17 [1] CRAN (R 3.6.2)
   R.methodsS3              1.8.1    2020-08-26 [1] CRAN (R 3.6.2)
   R.oo                     1.24.0   2020-08-26 [1] CRAN (R 3.6.2)
   R.utils                  2.10.1   2020-08-26 [1] CRAN (R 3.6.2)
   R6                       2.4.1    2019-11-12 [2] CRAN (R 3.6.2)
   rappdirs                 0.3.1    2016-03-28 [2] CRAN (R 3.6.2)
   RBGL                     1.62.1   2019-10-30 [1] Bioconductor  
   RColorBrewer             1.1-2    2014-12-07 [2] CRAN (R 3.6.2)
   Rcpp                     1.0.5    2020-07-06 [1] CRAN (R 3.6.2)
   RcppParallel             5.0.2    2020-06-24 [1] CRAN (R 3.6.2)
   RCurl                    1.98-1.2 2020-04-18 [1] CRAN (R 3.6.2)
   readxl                 * 1.3.1    2019-03-13 [2] CRAN (R 3.6.2)
   reshape2                 1.4.4    2020-04-09 [1] CRAN (R 3.6.2)
   Rgraphviz                2.30.0   2019-10-29 [1] Bioconductor  
   rio                      0.5.16   2018-11-26 [1] CRAN (R 3.6.2)
   rjson                    0.2.20   2018-06-08 [1] CRAN (R 3.6.2)
   rlang                    0.4.7    2020-07-09 [1] CRAN (R 3.6.2)
   rmarkdown                2.0      2019-12-12 [2] CRAN (R 3.6.2)
   robustbase               0.93-6   2020-03-23 [1] CRAN (R 3.6.2)
   rrcov                    1.5-5    2020-08-03 [1] CRAN (R 3.6.2)
   RSQLite                  2.2.0    2020-01-07 [2] CRAN (R 3.6.2)
   rstudioapi               0.11     2020-02-07 [1] CRAN (R 3.6.2)
   rsvd                     1.0.2    2019-07-29 [2] CRAN (R 3.6.2)
   Rtsne                    0.15     2018-11-10 [2] CRAN (R 3.6.2)
   S4Vectors              * 0.24.4   2020-04-09 [1] Bioconductor  
   sandwich                 2.5-1    2019-04-06 [2] CRAN (R 3.6.2)
   scales                   1.1.1    2020-05-11 [1] CRAN (R 3.6.2)
   scater                 * 1.14.6   2019-12-16 [1] Bioconductor  
   sessioninfo              1.1.1    2018-11-05 [2] CRAN (R 3.6.2)
   shape                    1.4.5    2020-09-13 [1] CRAN (R 3.6.2)
   shiny                    1.5.0    2020-06-23 [1] CRAN (R 3.6.2)
   shinyBS                  0.61     2015-03-31 [1] CRAN (R 3.6.2)
   shinydashboard           0.7.1    2018-10-17 [1] CRAN (R 3.6.2)
   shinyjs                  2.0.0    2020-09-09 [1] CRAN (R 3.6.2)
   SingleCellExperiment   * 1.8.0    2019-10-29 [1] Bioconductor  
   statmod                  1.4.34   2020-02-17 [1] CRAN (R 3.6.2)
   stringi                  1.5.3    2020-09-09 [1] CRAN (R 3.6.2)
   stringr                  1.4.0    2019-02-10 [2] CRAN (R 3.6.2)
   SummarizedExperiment   * 1.16.1   2019-12-19 [2] Bioconductor  
   survival                 3.1-8    2019-12-03 [3] CRAN (R 3.6.2)
   TH.data                  1.0-10   2019-01-21 [2] CRAN (R 3.6.2)
   tibble                   3.0.3    2020-07-10 [1] CRAN (R 3.6.2)
   tidyr                  * 1.1.2    2020-08-27 [1] CRAN (R 3.6.2)
   tidyselect               1.1.0    2020-05-11 [1] CRAN (R 3.6.2)
   tmvnsim                  1.0-2    2016-12-15 [1] CRAN (R 3.6.2)
   tsne                     0.1-3    2016-07-15 [2] CRAN (R 3.6.2)
   vctrs                    0.3.4    2020-08-29 [1] CRAN (R 3.6.2)
   vipor                    0.4.5    2017-03-22 [1] CRAN (R 3.6.2)
   viridis                  0.5.1    2018-03-29 [2] CRAN (R 3.6.2)
   viridisLite              0.3.0    2018-02-01 [2] CRAN (R 3.6.2)
   withr                    2.2.0    2020-04-20 [1] CRAN (R 3.6.2)
   xfun                     0.12     2020-01-13 [2] CRAN (R 3.6.2)
   XML                      3.99-0.3 2020-01-20 [1] CRAN (R 3.6.2)
   xtable                   1.8-4    2019-04-21 [2] CRAN (R 3.6.2)
   XVector                  0.26.0   2019-10-29 [2] Bioconductor  
   yaml                     2.2.1    2020-02-01 [1] CRAN (R 3.6.2)
   zip                      2.1.1    2020-08-27 [1] CRAN (R 3.6.2)
   zlibbioc                 1.32.0   2019-10-29 [2] Bioconductor  
   zoo                      1.8-8    2020-05-02 [1] CRAN (R 3.6.2)

**Comment by HelenaLC** [comment]
Okay. You are running R 3.6, but the current release is CATALYST 1.12 with Bioconductor 3.11 and R 4.0. Updating your software via updating R, then `install.packages("BiocManager")` and `BiocManager::install("CATALYST")` should resolve the issue.

**Comment by nayaracleite** [comment]
I updated and I still get the error: 
Error in prepData(samples_filtered, panel, md, features = panel$fcs_colname) : all(setdiff(unlist(panel_cols), "marker_class") %in% names(panel)) is not TRUE

spot check that all panel columns are in the flowSet object
> all(panel$fcs_colname %in% colnames(samples_filtered))
[1] TRUE
[session_info.txt](https://github.com/HelenaLC/CATALYST/files/5267842/session_info.txt)

─ Session info ───────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-09-23                  

─ Packages ───────────────────────────────────────────────────────────────────────────────
 package              * version  date       lib source        
 abind                  1.4-5    2016-07-21 [1] CRAN (R 4.0.2)
 assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.2)
 backports              1.1.10   2020-09-15 [1] CRAN (R 4.0.2)
 base64enc              0.1-3    2015-07-28 [1] CRAN (R 4.0.2)
 beeswarm               0.2.3    2016-04-25 [1] CRAN (R 4.0.2)
 Biobase              * 2.48.0   2020-04-27 [1] Bioconductor  
 BiocGenerics         * 0.34.0   2020-04-27 [1] Bioconductor  
 BiocNeighbors          1.6.0    2020-04-27 [1] Bioconductor  
 BiocParallel           1.22.0   2020-04-27 [1] Bioconductor  
 BiocSingular           1.4.0    2020-04-27 [1] Bioconductor  
 bitops                 1.0-6    2013-08-17 [1] CRAN (R 4.0.2)
 blob                   1.2.1    2020-01-20 [1] CRAN (R 4.0.2)
 boot                   1.3-25   2020-04-26 [1] CRAN (R 4.0.2)
 broom                  0.7.0    2020-07-09 [1] CRAN (R 4.0.2)
 car                    3.0-9    2020-08-11 [1] CRAN (R 4.0.2)
 carData                3.0-4    2020-05-22 [1] CRAN (R 4.0.2)
 CATALYST             * 1.12.2   2020-07-02 [1] Bioconductor  
 cellranger             1.1.0    2016-07-27 [1] CRAN (R 4.0.2)
 circlize               0.4.10   2020-06-15 [1] CRAN (R 4.0.2)
 cli                    2.0.2    2020-02-28 [1] CRAN (R 4.0.2)
 clue                   0.3-57   2019-02-25 [1] CRAN (R 4.0.2)
 cluster                2.1.0    2019-06-19 [1] CRAN (R 4.0.2)
 codetools              0.2-16   2018-12-24 [1] CRAN (R 4.0.2)
 colorspace             1.4-1    2019-03-18 [1] CRAN (R 4.0.2)
 ComplexHeatmap         2.4.3    2020-07-25 [1] Bioconductor  
 ConsensusClusterPlus   1.52.0   2020-04-27 [1] Bioconductor  
 cowplot              * 1.1.0    2020-09-08 [1] CRAN (R 4.0.2)
 crayon                 1.3.4    2017-09-16 [1] CRAN (R 4.0.2)
 curl                   4.3      2019-12-02 [1] CRAN (R 4.0.1)
 cytolib                2.0.3    2020-06-09 [1] Bioconductor  
 CytoML                 2.0.5    2020-06-15 [1] Bioconductor  
 data.table             1.13.0   2020-07-24 [1] CRAN (R 4.0.2)
 DBI                    1.1.0    2019-12-15 [1] CRAN (R 4.0.2)
 dbplyr                 1.4.4    2020-05-27 [1] CRAN (R 4.0.2)
 DelayedArray         * 0.14.1   2020-07-14 [1] Bioconductor  
 DelayedMatrixStats     1.10.1   2020-07-03 [1] Bioconductor  
 diffcyt              * 1.8.8    2020-08-05 [1] Bioconductor  
 digest                 0.6.25   2020-02-23 [1] CRAN (R 4.0.2)
 dplyr                * 1.0.2    2020-08-18 [1] CRAN (R 4.0.2)
 drc                    3.0-1    2016-08-30 [1] CRAN (R 4.0.2)
 edgeR                  3.30.3   2020-06-02 [1] Bioconductor  
 ellipsis               0.3.1    2020-05-15 [1] CRAN (R 4.0.2)
 evaluate               0.14     2019-05-28 [1] CRAN (R 4.0.1)
 fansi                  0.4.1    2020-01-08 [1] CRAN (R 4.0.2)
 flowCore             * 2.0.1    2020-06-09 [1] Bioconductor  
 FlowSOM                1.20.0   2020-04-27 [1] Bioconductor  
 flowWorkspace          4.0.6    2020-06-11 [1] Bioconductor  
 forcats              * 0.5.0    2020-03-01 [1] CRAN (R 4.0.2)
 foreign                0.8-80   2020-05-24 [1] CRAN (R 4.0.2)
 fs                     1.5.0    2020-07-31 [1] CRAN (R 4.0.2)
 generics               0.0.2    2018-11-29 [1] CRAN (R 4.0.2)
 GenomeInfoDb         * 1.24.2   2020-06-15 [1] Bioconductor  
 GenomeInfoDbData       1.2.3    2020-09-18 [1] Bioconductor  
 GenomicRanges        * 1.40.0   2020-04-27 [1] Bioconductor  
 GetoptLong             1.0.2    2020-07-06 [1] CRAN (R 4.0.2)
 ggbeeswarm             0.6.0    2017-08-07 [1] CRAN (R 4.0.2)
 ggcyto                 1.16.0   2020-04-27 [1] Bioconductor  
 ggplot2              * 3.3.2    2020-06-19 [1] CRAN (R 4.0.2)
 ggrepel                0.8.2    2020-03-08 [1] CRAN (R 4.0.2)
 ggridges               0.5.2    2020-01-12 [1] CRAN (R 4.0.2)
 GlobalOptions          0.1.2    2020-06-10 [1] CRAN (R 4.0.2)
 glue                   1.4.2    2020-08-27 [1] CRAN (R 4.0.2)
 graph                  1.66.0   2020-04-27 [1] Bioconductor  
 gridExtra              2.3      2017-09-09 [1] CRAN (R 4.0.2)
 gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.2)
 gtools                 3.8.2    2020-03-31 [1] CRAN (R 4.0.2)
 haven                  2.3.1    2020-06-01 [1] CRAN (R 4.0.2)
 hexbin                 1.28.1   2020-02-03 [1] CRAN (R 4.0.2)
 hms                    0.5.3    2020-01-08 [1] CRAN (R 4.0.2)
 htmltools              0.5.0    2020-06-16 [1] CRAN (R 4.0.2)
 httr                   1.4.2    2020-07-20 [1] CRAN (R 4.0.2)
 igraph                 1.2.5    2020-03-19 [1] CRAN (R 4.0.2)
 IRanges              * 2.22.2   2020-05-21 [1] Bioconductor  
 irlba                  2.3.3    2019-02-05 [1] CRAN (R 4.0.2)
 jpeg                   0.1-8.1  2019-10-24 [1] CRAN (R 4.0.2)
 jsonlite               1.7.1    2020-09-07 [1] CRAN (R 4.0.2)
 knitr                  1.30     2020-09-22 [1] CRAN (R 4.0.2)
 lattice                0.20-41  2020-04-02 [1] CRAN (R 4.0.2)
 latticeExtra           0.6-29   2019-12-19 [1] CRAN (R 4.0.2)
 lifecycle              0.2.0    2020-03-06 [1] CRAN (R 4.0.2)
 limma                  3.44.3   2020-06-12 [1] Bioconductor  
 lme4                   1.1-23   2020-04-07 [1] CRAN (R 4.0.1)
 locfit                 1.5-9.4  2020-03-25 [1] CRAN (R 4.0.2)
 lubridate              1.7.9    2020-06-08 [1] CRAN (R 4.0.2)
 magrittr               1.5      2014-11-22 [1] CRAN (R 4.0.2)
 MASS                   7.3-53   2020-09-09 [1] CRAN (R 4.0.2)
 Matrix                 1.2-18   2019-11-27 [1] CRAN (R 4.0.2)
 matrixStats          * 0.56.0   2020-03-13 [1] CRAN (R 4.0.2)
 minqa                  1.2.4    2014-10-09 [1] CRAN (R 4.0.2)
 modelr                 0.1.8    2020-05-19 [1] CRAN (R 4.0.2)
 multcomp               1.4-13   2020-04-08 [1] CRAN (R 4.0.2)
 munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.2)
 mvtnorm                1.1-1    2020-06-09 [1] CRAN (R 4.0.2)
 ncdfFlow               2.34.0   2020-04-27 [1] Bioconductor  
 nlme                   3.1-149  2020-08-23 [1] CRAN (R 4.0.2)
 nloptr                 1.2.2.2  2020-07-02 [1] CRAN (R 4.0.2)
 nnls                   1.4      2012-03-19 [1] CRAN (R 4.0.2)
 openxlsx               4.2.2    2020-09-17 [1] CRAN (R 4.0.2)
 pillar                 1.4.6    2020-07-10 [1] CRAN (R 4.0.2)
 pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.2)
 plotrix                3.7-8    2020-04-16 [1] CRAN (R 4.0.2)
 plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.0.2)
 png                    0.1-7    2013-12-03 [1] CRAN (R 4.0.2)
 purrr                * 0.3.4    2020-04-17 [1] CRAN (R 4.0.2)
 R6                     2.4.1    2019-11-12 [1] CRAN (R 4.0.2)
 RBGL                   1.64.0   2020-04-27 [1] Bioconductor  
 RColorBrewer           1.1-2    2014-12-07 [1] CRAN (R 4.0.2)
 Rcpp                   1.0.5    2020-07-06 [1] CRAN (R 4.0.2)
 RcppParallel           5.0.2    2020-06-24 [1] CRAN (R 4.0.2)
 RCurl                  1.98-1.2 2020-04-18 [1] CRAN (R 4.0.2)
 readr                * 1.3.1    2018-12-21 [1] CRAN (R 4.0.2)
 readxl                 1.3.1    2019-03-13 [1] CRAN (R 4.0.2)
 reprex                 0.3.0    2019-05-16 [1] CRAN (R 4.0.2)
 reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.0.2)
 Rgraphviz              2.32.0   2020-04-27 [1] Bioconductor  
 rio                    0.5.16   2018-11-26 [1] CRAN (R 4.0.2)
 rjson                  0.2.20   2018-06-08 [1] CRAN (R 4.0.2)
 rlang                  0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
 rmarkdown              2.3      2020-06-18 [1] CRAN (R 4.0.2)
 RProtoBufLib           2.0.0    2020-04-27 [1] Bioconductor  
 rstudioapi             0.11     2020-02-07 [1] CRAN (R 4.0.2)
 rsvd                   1.0.3    2020-02-17 [1] CRAN (R 4.0.2)
 Rtsne                  0.15     2018-11-10 [1] CRAN (R 4.0.2)
 rvest                  0.3.6    2020-07-25 [1] CRAN (R 4.0.2)
 S4Vectors            * 0.26.1   2020-05-16 [1] Bioconductor  
 sandwich               2.5-1    2019-04-06 [1] CRAN (R 4.0.2)
 scales                 1.1.1    2020-05-11 [1] CRAN (R 4.0.2)
 scater               * 1.16.2   2020-06-26 [1] Bioconductor  
 sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.2)
 shape                  1.4.5    2020-09-13 [1] CRAN (R 4.0.2)
 SingleCellExperiment * 1.10.1   2020-04-28 [1] Bioconductor  
 statmod                1.4.34   2020-02-17 [1] CRAN (R 4.0.2)
 stringi                1.5.3    2020-09-09 [1] CRAN (R 4.0.2)
 stringr              * 1.4.0    2019-02-10 [1] CRAN (R 4.0.2)
 SummarizedExperiment * 1.18.2   2020-07-14 [1] Bioconductor  
 survival               3.2-3    2020-06-13 [1] CRAN (R 4.0.2)
 TH.data                1.0-10   2019-01-21 [1] CRAN (R 4.0.2)
 tibble               * 3.0.3    2020-07-10 [1] CRAN (R 4.0.2)
 tidyr                * 1.1.2    2020-08-27 [1] CRAN (R 4.0.2)
 tidyselect             1.1.0    2020-05-11 [1] CRAN (R 4.0.2)
 tidyverse            * 1.3.0    2019-11-21 [1] CRAN (R 4.0.2)
 tsne                   0.1-3    2016-07-15 [1] CRAN (R 4.0.2)
 vctrs                  0.3.4    2020-08-29 [1] CRAN (R 4.0.2)
 vipor                  0.4.5    2017-03-22 [1] CRAN (R 4.0.2)
 viridis                0.5.1    2018-03-29 [1] CRAN (R 4.0.2)
 viridisLite            0.3.0    2018-02-01 [1] CRAN (R 4.0.1)
 withr                  2.3.0    2020-09-22 [1] CRAN (R 4.0.2)
 xfun                   0.17     2020-09-09 [1] CRAN (R 4.0.2)
 XML                    3.99-0.5 2020-07-23 [1] CRAN (R 4.0.2)
 xml2                   1.3.2    2020-04-23 [1] CRAN (R 4.0.2)
 XVector                0.28.0   2020-04-27 [1] Bioconductor  
 yaml                   2.2.1    2020-02-01 [1] CRAN (R 4.0.2)
 zip                    2.1.1    2020-08-27 [1] CRAN (R 4.0.2)
 zlibbioc               1.34.0   2020-04-27 [1] Bioconductor  
 zoo                    1.8-8    2020-05-02 [1] CRAN (R 4.0.2)
